### ISSUE TITLE
Webpack loader for import maps

### ISSUE THREAD

**Issue by emilhauk** [eik-lib/issues#11]
Not exactly fully featured or anything, but here's a loader for using import maps in webpack: https://www.npmjs.com/package/webpack-import-maps-loader

This is just ment to be FYI. You may close this "issue" :)

**Comment by trygve-lie** [comment]
Awesome! I'll have a look and see if we can use it for a eik plugin. Thanks a lot!

**Comment by emilhauk** [comment]
Slight update on this. I could never get webpack to ignore "regular" imports, and the loader never reflected this.

I have updated the loader to throw an error if this is attempted. If you know a way around this, please let me know/push a pr to https://github.com/emilhauk/webpack-import-maps-loader!

**Comment by trygve-lie** [comment]
There is now a webpack plugin available: https://github.com/eik-lib/webpack-plugin
